### ISSUE TITLE
perfect...except images won't display

### ISSUE THREAD

**Issue by dezziegirl** [danny-englander/drupal-bamboo-slideshow#2]
Love your theme and have carefully followed steps for the slideshow. I placed the block on the site and can see title and description for slides but the slide images aren't displaying on the page. I can see the images in the bamboo-slide-image folder. Any advice?

**Comment by dezziegirl** [comment]
I fixed the problem - I used the wrong slider block! Thanks for making a great slider :)

**Comment by danny-englander** [comment]
Great, glad you got it sorted out. Thanks!

**Comment by Chriss-Kyyti** [comment]
I seem to have the same problem. Only the "Link to Self Slideshow Block" seems to work out of the box. "Content Reference" block style does not show the image! Otherwise this was easy to set up. Thanks for all the work.
